Test : ReportRepositoryTest-ck done
Bros4Kkun/Back-end pull request #67
Opened 2022-04-17 10:13 UTC by kimchanggun

ReportRepositoryTest done

2022-04-18 04:46 UTC, TaegyunWoo requested changes
수정해서 다시 올려줘!

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User reportUser = new User(accountId, password, realName, nickname, phoneNumber, accountNumber);
37번째 줄은 필요없는 내용이니, 삭제해줘~!

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User findUserByAccountId = userRepository.findUserByAccountId(accountId).get();
Report를 저장할 때 User가 `신고자`랑 `피신고자`로 구분되니까, 변수명을 수정하는게 어떨까. 아래처럼...

```java
//기존
User findUserByAccountId = userRepository.findUserByAccountId(accountId).get();

//수정
User reporter = userRepository.findUserByAccountId(accountId).get();
```

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User haveReportedUser = new User(accountId1, password1, realName1, nickname1, phoneNumber1, accountNumber1);
48번째 줄도 필요없으니까 삭제!

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User findUserByAccountId1 = userRepository.findUserByAccountId(accountId1).get();
여기도 마찬가지로, `신고자`랑 `피신고자`를 명확하게 구분하는게 나아보여. 아래처럼..

```java
//기존
User findUserByAccountId1 = userRepository.findUserByAccountId(accountId1).get();

//수정
User haveReportedUser = userRepository.findUserByAccountId(accountId1).get();
```

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User reportUser = new User(accountId, password, realName, nickname, phoneNumber, accountNumber);
74번째 줄은 필요없는 내용이므로 삭제

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User findUserByAccountId = userRepository.findUserByAccountId(accountId).get();
마찬가지로 변수명을 명확한 의미로 수정하는 것이 좋아보여.

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User haveReportedUser = new User(accountId1, password1, realName1, nickname1, phoneNumber1, accountNumber1);
85번째줄 삭제

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User findUserByAccountId1 = userRepository.findUserByAccountId(accountId1).get();
변수명 수정

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    reportRepository.saveReport(findUserByAccountId, findUserByAccountId1, category, content);
**모든** Report를 조회하는 것을 테스트하는게 목적이니까, 최소 2개 이상의 Report를 저장하고 검증해야 할 것 같아!

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User reportUser = new User(accountId, password, realName, nickname, phoneNumber, accountNumber);
119번째 줄 삭제

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User findUserByAccountId = userRepository.findUserByAccountId(accountId).get();
변수명 수정

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User haveReportedUser = new User(accountId1, password1, realName1, nickname1, phoneNumber1, accountNumber1);
130번째 줄 삭제

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    User findUserByAccountId1 = userRepository.findUserByAccountId(accountId1).get();
변수명 수정

2022-04-18 04:46 UTC, TaegyunWoo commented on src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> +    reportRepository.findAll(1,1);
- 141번째 줄의 내용과 142번째 줄 내용을 보면, `findAll(1,1)`이 반복되어 호출됨.
- 따라서 141번째 줄 삭제.

2022-04-19 06:55 UTC, kimchanggun reviewed
수정사항 수정.

2022-04-19 08:16 UTC, TaegyunWoo approved these changes

2022-04-19 08:16 UTC, merged